name: Download List & Vis

on:
  schedule:
    - cron: "0 0 1,11,21 * *"
  workflow_dispatch:

env:
  WEBHOOK: ${{ secrets.WEBHOOK }}

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependency
        run: |
          sudo apt-get purge google-chrome-stable
          sudo apt-get purge chromium-browser
          sudo apt-get install -y chromium-browser
          pip install requests pandas xlrd selenium seaborn matplotlib
          sudo cp prop/DoHyeon-Regular.ttf /usr/share/fonts/
          sudo fc-cache -f -v
          rm ~/.cache/matplotlib -fr

      - name: Run Script
        run: |
          rm -f prop/*/*.png
          rm -f prop/*/*.md
          rm -rf prop/time
          python main.py

      - name: Move XLS File to data Directory
        run: |
          mkdir -p data/
          mv *.xls data/

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data
          git commit -m ":monocle_face: Add: Data" || echo "data: No changes to commit"
          git add prop/*/*.md
          git commit -m ":rocket: Docs: Rank" || echo "prop/*/*.md: No changes to commit"
          git add prop/*/*.png
          git commit -m ":art: Update: Visualization" || echo "prop/*/*.png: No changes to commit"
          git add prop/time.tsv
          git add prop/time
          git commit -m ":alarm_clock: Update: Time Series" || echo "time.tsv, prop/time: No changes to commit"
          git add -A
          git commit -m ":bento: Update: Etc." || echo "Etc.: No changes to commit"
          git push
